# Generated by Django 4.0.1 on 2022-03-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us',
        ),
    ]
